### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by vbelyaev89** [yuichiro-s/chainer-bot#1]
Hi, I'd like to thank you for this fabulous implementation of seq2seq. I haven't tried it yet, now just revising the code and trying to figure out how it works.
As far as I understood you didn't implement the reverse of input sequence during training, did you?

By the way, this guys http://arxiv.org/abs/1510.03055 took a step forward. Hope it might be interesting =)

**Comment by yuichiro-s** [comment]
Hi, thanks for the comment. I haven't implemented reversing the input yet, but I will soon. And thanks for the paper! The paper discusses the problem I'm also suffering.
